### ISSUE TITLE
What is a "significant" tree for survey measurement?

### ISSUE THREAD

**Issue by mruth-tesc** [Global-Evergreening-Alliance/Sandbox#12]
The prototype survey123 form from the Uganda workshop (Feb 2020) included a section for the collection of data on "significant trees".   This survey element did not make sense during the field trial for many reasons.  GEA need to develop a protocol to allow enumerators to know what trees (if any) meet the criteria of significance for capturing data such as species, DBH (height?) or other metrics.  
During the prototype field trial in Nakasongola, enumerators observed that trees were present across all farmers' lands and lacked definition about whether to invest effort in collection of tree metrics.  Some data concerning significant trees was captured during the field trial, but the trees to be measured were chosed arbitrarily by each enumerator.  
Measuring many trees is an effort and time commitment that risks making survey fulfillment a long process.

**Comment by talialiney** [comment]
Significant trees section of the survey is being deleted. Replacement section TBC following discussion with Chris
